---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

title: Cohen's Homepage

background:
  image: https://cdnb.artstation.com/p/assets/images/images/006/897/659/large/mikael-gustafsson-wallpaper-mikael-gustafsson.jpg
  blur: sm # sm, md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 100 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 100 # 0-100

theme: dark
color: slate

useEqualHeights: true

layout:
  Media:
    header: true
    style: row
    columns: 3
  Books:
    header: true
    style: row
    columns: 3
  Media Management:
    header: true
    style: row
    columns: 3
  Downloaders:
    header: true
    style: column
  Storage:
    header: true
    style: column
  Network:
    header: true
    style: column
  Syncthing Instances:
    header: true
    style: column